### ISSUE TITLE
How to add yolo wrapper to the pipeline.

### ISSUE THREAD

**Issue by adinath1233** [deepdoctection/deepdoctection#371]
I want to use a custom YoloV10 model as "ImageLayoutService" within the pipeline.
I understand that i have to write a new wrapper in extern.
Can you help me with the same ?

### Inference using ultralytics and yolo
```
from ultralytics import YOLO

model = YOLO("yolov10n.pt")
results = model("image.jpg")

for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
```

### I tried writing a new file : yolodetector.py, similar to d2detect.py and pdftext.py

```
def _yolo10_to_detectresult(results, width: int, height: int) -> list[DetectionResult]:

    all_results: list[DetectionResult] = []
    names = results.names
    name_keys = list(names.keys())  
    confidence = results.speed.get('inference', 0) / 100 # normalize the data
    
    # Loop through each detected box
    for i, box in enumerate(results.boxes.xyxy):
        x1, y1, x2, y2 = box.tolist()
        class_id = name_keys[i % len(name_keys)]
        class_name = names[class_id]
        

        detection = DetectionResult(
            box=[x1, y1, x2, y2],
            score=confidence,  
            class_id=class_id,
            class_name=class_name,
        )
       
        # Append the DetectionResult to the list
        all_results.append(detection)
    print("all_results: ", all_results)

    return all_results

def predict_yolo10(np_img: PixelValues, model, conf_threshold: float = 0.2, iou_threshold: float = 0.8) -> list[DetectionResult]:

    height, width = np_img.shape[:2]
    results = model(source=np_img, conf=conf_threshold, iou=iou_threshold)[0]
    all_results = _yolo10_to_detectresult(results, width, height)
    
    return all_results

class YoloDetector(ObjectDetector):
    def __init__(self, 
                 conf_threshold: float = 0.2, 
                 iou_threshold: float = 0.8, 
                 model_weights: PathLikeOrStr = None, 
                 categories: Mapping[int, TypeOrStr] = None) -> None:

        self.name = "yoloV10_detector"
        self.model_id = self.get_model_id()
        self.conf_threshold = conf_threshold
        self.iou_threshold = iou_threshold

        # Load YOLOv10 model with specified weights
        self.model = YOLOv10(model_weights)

        if categories is None:
            raise ValueError("A dictionary of category mappings must be provided.")
        self.categories = ModelCategories(init_categories=categories)


    def predict(self, np_img: PixelValues) -> list[DetectionResult]:
        return predict_yolo10(np_img, self.model, self.conf_threshold, self.iou_threshold)


    def clone(self) -> YoloDetector:
        return self.__class__(conf_threshold=self.conf_threshold, 
                              iou_threshold=self.iou_threshold, 
                              model_weights=self.model.model_path)

    def get_category_names(self) -> tuple[ObjectTypes, ...]:
        return self.categories.get_categories(as_dict=False)
        
```

### I tried using this file within the pipeline after registering the model unfortunately it isn't working. What changes should I make to make it work similar to layout parser.

**Comment by JaMe76** [comment]
I am not quite sure how to help, for what I have seen so far, this wrapper should be working. 

Can you elaborate more on what specific is not working? Do you get an error message or is the output not what you expect? 

One thing that it is worth to check because I haven't worked with `ultralytics`: What is the raw bounding box output of the model? Relative or absolute coordinates? If the output is in terms of relative coordinates, you need to specify that because the default value of `DetectionResult` is `True`.

**Comment by adinath1233** [comment]
These are the coordinate from YOLO:

![Screenshot from 2024-11-06 15-35-14](https://github.com/user-attachments/assets/a821a279-b5bb-4f16-974b-f1da1e425d9a)

### Inference output:

## Layout Parser + PDF plumber:
![layout](https://github.com/user-attachments/assets/7912aeb9-5560-43ce-bacc-d050fc776ea7)

result:
![Screenshot from 2024-11-06 15-31-17](https://github.com/user-attachments/assets/ed5620de-49d3-4861-b5d4-d3415b1b9399)


## YOLO+PDF plumber:
![yolo](https://github.com/user-attachments/assets/a7779dba-48b1-4e1d-9373-a7ef43b224a6)

result:
![Screenshot from 2024-11-06 15-32-15](https://github.com/user-attachments/assets/350124bc-f932-4b8c-b462-7f839867676e)

**Althought result from yolo is different labels / regions being identified by the model, when pdf plumber is being used the result is all lines.

Is data being send properly from YOLO to PDF plumber?**

### YOLO Pipeline: 
```
model_name = "yolo/yolo10x/yolov10x_best.pt"
path = "Examples/data/sample.pdf"

@dd.object_types_registry.register("YOLOTYPE")
class YOLOTYPE(dd.ObjectTypes):
    """Additional YOLO labels not registered yet"""

    CAPTION ="Caption",
    FOOTNOTE = "Footnote",
    FORMULA = "Formula",
    LIST_ITEM = "List-item",
    PAGE_FOOTER = "Page-footer",
    PAGE_HEADER = "Page-header",
    PICTURE =  "Picture",
    SECTION_HEADER = "Section-header",
    TABLE = "Table",
    TEXT = "Text",
    TITLE = "Title"

dd.ModelCatalog.register(model_name, dd.ModelProfile(
    name=model_name,
    description="YOLOv10 model for layout analysis",
    tp_model=False,
    size=[],
    categories={
        1: YOLOTYPE.CAPTION,
        2: YOLOTYPE.FOOTNOTE,
        3: YOLOTYPE.FORMULA,
        4: YOLOTYPE.LIST_ITEM,
        5: YOLOTYPE.PAGE_FOOTER,
        6: YOLOTYPE.PAGE_HEADER,
        7: YOLOTYPE.PICTURE,
        8: YOLOTYPE.SECTION_HEADER,
        9: YOLOTYPE.TABLE,
        10: YOLOTYPE.TEXT,
        11: YOLOTYPE.TITLE,
    },
    model_wrapper="YoloDetector"
))

yolo_weights_path = dd.ModelCatalog.get_full_path_weights(model_name)
categories = dd.ModelCatalog.get_profile(model_name).categories
cats = [
        YOLOTYPE.CAPTION,
        YOLOTYPE.LIST_ITEM,
        YOLOTYPE.PAGE_HEADER,
        YOLOTYPE.SECTION_HEADER,
        YOLOTYPE.TEXT,
        YOLOTYPE.TITLE,
        ]

yolo_detector = YoloDetector(model_weights=yolo_weights_path, categories=categories)

layout_service = ImageLayoutService(yolo_detector)

text_detector=PdfPlumberTextDetector()
text=TextExtractionService(text_detector)

map_comp = dd.MatchingService(parent_categories=[
                                                YOLOTYPE.CAPTION,
                                                YOLOTYPE.LIST_ITEM,
                                                YOLOTYPE.PAGE_HEADER,
                                                YOLOTYPE.SECTION_HEADER,
                                                YOLOTYPE.TEXT,
                                                YOLOTYPE.TITLE,
                                                ], 
                              child_categories=[dd.LayoutType.WORD], 
                              matching_rule='ioa', threshold=0.3,
                              max_parent_only=True)
text_order_comp = dd.TextOrderService(text_container=dd.LayoutType.WORD,
                                     text_block_categories=cats,
                                     floating_text_block_categories=[
                                                                    YOLOTYPE.CAPTION,
                                                                    YOLOTYPE.LIST_ITEM,
                                                                    YOLOTYPE.PAGE_HEADER,
                                                                    YOLOTYPE.SECTION_HEADER,
                                                                    YOLOTYPE.TEXT,
                                                                    YOLOTYPE.TITLE,
                                                                    ],
                                     include_residual_text_container=True)

page_parsing = dd.PageParsingService(text_container=dd.LayoutType.WORD,
                                         floating_text_block_categories=[
                                                                        YOLOTYPE.CAPTION,
                                                                        YOLOTYPE.LIST_ITEM,
                                                                        YOLOTYPE.PAGE_HEADER,
                                                                        YOLOTYPE.SECTION_HEADER,
                                                                        YOLOTYPE.TEXT,
                                                                        YOLOTYPE.TITLE,
                                                                        ],
                                         include_residual_text_container=True)

pipe_comp_list = [layout_service,text,map_comp,text_order_comp]
pipe = dd.DoctectionPipe(pipeline_component_list=pipe_comp_list,page_parsing_service=page_parsing)

df = pipe.analyze(path=path)
df.reset_state()
for dp in df:
    print(dp.text)
```

**Comment by JaMe76** [comment]
One thing I observe is that you do not specify the conversion of YOLOTYPE member to Layout sections (cf. https://github.com/deepdoctection/notebooks/blob/main/Running_pre_trained_models_from_third_party_libraries.ipynb `cell[15]`). 

```python
from deepdoctection.datapoint.view import IMAGE_ANNOTATION_TO_LAYOUTS, Layout

IMAGE_ANNOTATION_TO_LAYOUTS.update({i: Layout for i in YOLOTYPE})
```

You should add this after defining your `YOLOTYPE` class.

**Comment by adinath1233** [comment]
Thank You for your prompt response, 
I added this line still getting same output.

**Comment by JaMe76** [comment]
If you output:

```python
print(dp.layouts)
```

what do you get? Only lines? Or do you also get some `YOLOTYPE`s?

**Comment by JaMe76** [comment]
You will get lines if you map assign words only to some layout sections unless you specify `include_residual_text_container=False`. If you are not interested in text of these layout sections simply set `include_residual_text_container=False`.

**Comment by adinath1233** [comment]
> ```python
> layouts
> ```

I am getting LINES dp.layouts.

Output:
Layout(active=True, _annotation_id='7d97201b-0d66-3a70-b348-3129007d981e', service_id='f10aa678', model_id=None, session_id=None, category_name=<LayoutType.LINE>, _category_name=<LayoutType.LINE>, category_id=1, score=None, sub_categories={<Relationships.READING_ORDER>: CategoryAnnotation(active=True, _annotation_id='c52a3972-372b-3ee8-9c4f-2f6f5e288d65', service_id='f10aa678', model_id=None, session_id=None, category_name=<Relationships.READING_ORDER>, _category_name=<Relationships.READING_ORDER>, category_id=93, score=None, sub_categories={}, relationships={})}, relationships={<Relationships.CHILD>: ['0446e645-4bc0-377c-ba1c-44a16c314d2b']}, bounding_box=BoundingBox(absolute_coords=True, ulx=1231.0, uly=3026.0, lrx=1311.0, lry=3064.0, height=38.0, width=80.0)),

**Comment by adinath1233** [comment]
> You will get lines if you map assign words only to some layout sections unless you specify `include_residual_text_container=False`. If you are not interested in text of these layout sections simply set `include_residual_text_container=False`.

I tried above by giving False I am not getting any output.

**Comment by JaMe76** [comment]
There seem to be some issue with the configuration, yet I do not see where.

**Comment by adinath1233** [comment]
> At the beginning of the script change the log level to debug:
> 
> ```python
> import os
> os.environ["LOG_LEVEL"]="DEBUG"
> ```
> 
> Also let me know what deepdoctection you are working with. You are using a `MatchingService` class that is not the one in the latest version.

I am using 
Name: deepdoctection
Version: 0.33

**Comment by adinath1233** [comment]
> At the beginning of the script change the log level to debug:
> 
> ```python
> import os
> os.environ["LOG_LEVEL"]="DEBUG"
> ```
> 
> Also let me know what deepdoctection you are working with. You are using a `MatchingService` class that is not the one in the latest version.

Can I share the response from the console?

**Comment by JaMe76** [comment]
> > At the beginning of the script change the log level to debug:
> > ```python
> > import os
> > os.environ["LOG_LEVEL"]="DEBUG"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also let me know what deepdoctection you are working with. You are using a `MatchingService` class that is not the one in the latest version.
> 
> Can I share the response from the console?

Yes, just remove any personal details.

**Comment by adinath1233** [comment]
> > > At the beginning of the script change the log level to debug:
> > > ```python
> > > import os
> > > os.environ["LOG_LEVEL"]="DEBUG"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also let me know what deepdoctection you are working with. You are using a `MatchingService` class that is not the one in the latest version.
> > 
> > 
> > Can I share the response from the console?
> 
> Yes, just remove any personal details.



```
(docAi) adinat@adinath-Sangaj:~/Python Ml/deepdoctection$ python -m Examples.yolopdf[1106 18:10.59 @file_utils.py:31]  INF  PyTorch version 2.4.1+cu118 available.[1106 18:10.59 @file_utils.py:69]  INF  Disabling Tensorflow because USE_TORCH is set/home/adinat/Python Ml/yolov10/ultralytics/nn/tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.  ckpt = torch.load(file, map_location="cpu")[1106 18:11.04 @doctectionpipe.py:84]  INF  Processing sample_0.pdf0: 640x512 5 List-items, 1 Page-footer, 1 Page-header, 4 Section-headers, 10 Texts, 1 Title, 263.2msSpeed: 4.9ms preprocess, 263.2ms inference, 44.4ms postprocess per image at shape (1, 3, 640, 512)[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @maputils.py:104]  WRN  MappingContextManager error. Will filter annotation[1106 18:11.07 @context.py:133]  INF  ImageLayoutService total: 1.3498 sec.[1106 18:11.07 @context.py:133]  INF  TextExtractionService total: 0.3616 sec.[1106 18:11.07 @context.py:133]  INF  MatchingService total: 0.0005 sec.[1106 18:11.07 @context.py:133]  INF  TextOrderService total: 0.0489 sec.PAGE : 1LINE: 6679LINE: Intelligence(www.aaai.org).Allrightsreserved.LINE: wardselectionandLassoregularization(GuyonandElisseeffLINE: Copyright(cid:13)c 2021,AssociationfortheAdvancementofArtificialLINE: nessforprediction.Commonly-usedtechniquessuchasfor-LINE: Oneobviousmotivationisexpectedperformanceimprove-LINE: ciously picking a subset of features based on their useful-LINE: Why is deep learning worth exploring for tabular data?LINE: Featureselection:Featureselectionbroadlyreferstojudi-LINE: 2016;ShavittandSegal2018;Xuetal.2019).LINE: RelatedWorkLINE: ulardecisionmanifolds(Goodfellow,Bengio,andCourvilleLINE: biasoftencausesthemtofailtofindoptimalsolutionsfortab-LINE: pre-trainingtopredictmaskedfeatures(seeFig.2).LINE: vastlyoverparametrized–thelackofappropriateinductiveLINE: icantperformanceimprovementsbyusingunsupervisedLINE: convolutionallayersormulti-layerperceptrons(MLPs)areLINE: 4. Finally,forthefirsttimefortabulardata,weshowsignif-LINE: architecturesarenotwell-suitedfortabulardata:e.g.stackedLINE: thecontributionofeachfeaturetothetrainedmodel.LINE: arefasttotrain.Second,becausepreviously-proposedDNNLINE: arecombined,andglobalinterpretabilitywhichquantifiesLINE: importantconcerninmanyreal-worldapplications;(iii)theyLINE: thatvisualizestheimportanceoffeaturesandhowtheyLINE: bleform,e.g.(Lundberg,Erion,andLee2018)–thisisanLINE: enablestwokindsofinterpretability:localinterpretabilityLINE: arepopularpost-hocexplainabilitymethodsfortheirensem-LINE: gressionproblemsfromdifferentdomains;and(ii)TabNetLINE: intheirbasicform(e.g.bytrackingdecisionnodes)andthereLINE: ingmodelsonvariousdatasetsforclassificationandre-LINE: commonintabulardata;and(ii)theyarehighlyinterpretableLINE: TabNetoutperformsorisonparwithothertabularlearn-LINE: foldswithapproximatelyhyperplaneboundarieswhichareLINE: 3. Abovedesignchoicesleadtotwovaluableproperties:(i)LINE: fits:(i)theyarerepresentionallyefficientfordecisionmani-LINE: learningarchitectureforfeatureselectionandreasoning.LINE: Why?First,becauseDT-basedapproacheshavecertainbene-LINE: andvanderSchaar2019),TabNetemploysasingledeepLINE: trees(DTs)stilldominatingmostapplications(Bansal2020).LINE: lectionmethodslike(Chenetal.2018)or(Yoon,Jordon,LINE: mains under-explored, with variants of ensemble decisionLINE: foreachinput,andunlikeotherinstance-wisefeaturese-LINE: tures),(Chuietal.2018),deeplearningfortabulardatare-LINE: featureselectionisinstance-wise,e.g.itcanbedifferentLINE: AI(asitiscomprisedofanycategoricalandnumericalfea-LINE: is used for the most salient features (see Fig. 1). ThisLINE: Despitebeingthemostcommondatatypeinreal-worldLINE: terpretabilityandbetterlearningasthelearningcapacityLINE: seesuchsuccesswithacanonicalarchitectureistabulardata.LINE: tures to reason from at each decision step, enabling in-LINE: tions,fueltherapidprogress.OnedatatypethathasyettoLINE: 2. TabNet uses sequential attention to choose which fea-LINE: efficientlyencodetherawdataintomeaningfulrepresenta-LINE: enablingflexibleintegrationintoend-to-endlearning.LINE: (Amodeietal.2015).Forthese,canonicalarchitecturesthatLINE: andistrainedusinggradientdescent-basedoptimization,LINE: withimages(Heetal.2015),text(Laietal.2015)andaudioLINE: 1. TabNetinputsrawtabulardatawithoutanypreprocessingLINE: Deepneuralnetworks(DNNs)haveshownnotablesuccessLINE: data,TabNet.Themaincontributionsaresummarizedas:LINE: IntroductionLINE: WeproposeanewcanonicalDNNarchitecturefortabularLINE: semi-supervisedlearning(Daietal.2017).LINE: ingperformancewhenunlabeleddataisabundant.LINE: generativemodeling(Radford,Metz,andChintala2015)andLINE: self-supervisedlearningfortabulardata,significantlyimprov-LINE: domainadaptation(Goodfellow,Bengio,andCourville2016),LINE: plusinsightsintoitsglobalbehavior.Finally,wedemonstrateLINE: manyvaluableapplicationscenariosincludingdata-efficientLINE: tabulardatasetsandyieldsinterpretablefeatureattributionsLINE: to-endmodelsallowrepresentationlearningwhichenablesLINE: othervariantsonawiderangeofnon-performance-saturatedLINE: fromstreamingdataandperhapsmostimportantly(iv)end-LINE: salient features. We demonstrate that TabNet outperformsLINE: in tree-based tabular data learning methods; (iii) learningLINE: efficientlearningasthelearningcapacityisusedforthemostLINE: needforfeatureengineering,whichiscurrentlyakeyaspectLINE: fromateachdecisionstep,enablinginterpretabilityandmoreLINE: typeslikeimagesalongwithtabulardata;(ii)alleviatingtheLINE: usessequentialattentiontochoosewhichfeaturestoreasonLINE: multitudeofbenefits:(i)efficientlyencodingmultipledataLINE: icaldeeptabulardatalearningarchitecture,TabNet.TabNetLINE: basedend-to-endlearningfortabulardatawhichcanhaveaLINE: Weproposeanovelhigh-performanceandinterpretablecanon-LINE: addition,unliketreelearning,DNNsenablegradientdescent-LINE: AbstractLINE: mentsparticularlyforlargedatasets(Hestnessetal.2017).InLINE: soarik@google.com,tpfister@google.comLINE: Sunnyvale,CALINE: GoogleCloudAILINE: SercanO¨.Arık,TomasPfisterLINE: TabNet: Attentive Interpretable Tabular LearningLINE: TheThirty-FifthAAAIConferenceonArtificialIntelligence(AAAI-21)<class 'deepdoctection.datapoint.view.Table'>Table found 
```

**Comment by JaMe76** [comment]
Logs are looking weird.

Can you also add: 

```python
os.environ["STD_OUT_VERBOSE"]="TRUE"
```

and generating a logger file instead of pasting everything from console:

```python
dd.auto_set_dir()
```

You can check the logger dir with:

```python
print(dd.get_logger_dir())
```

**Comment by adinath1233** [comment]
I have added the above code here it is a logger file you asked for
[log.json](https://github.com/user-attachments/files/17656011/log.json)

**Comment by JaMe76** [comment]
OK, I  suspect what might be the reason of the issue:

You write the `YOLOTYPE` string members with a capital letter, e.g. "Caption". There is an internal conversion that lower cases all strings: "caption". I had to add this logic in an earlier release, when changing the naming convention. When mapping back to proper enum types it does not find an entry "caption", (because only "Caption" is registered) and this results that all yolo layout detections are being filtered out.

To fix that I suggest to not work with `YOLOTYPE`. Use `dd.LayoutType`. You can check that all your `YOLOTYPE` members are also available as `dd.LayoutType`:

```python
class LayoutType(ObjectTypes):
    """Layout types"""

    TABLE = "table"
    TABLE_ROTATED = "table_rotated"
    FIGURE = "figure"
    LIST = "list"
    TEXT = "text"
    TITLE = "title"
    LOGO = "logo"
    SIGNATURE = "signature"
    CAPTION = "caption"
    FOOTNOTE = "footnote"
    FORMULA = "formula"
    PAGE_FOOTER = "page_footer"
    PAGE_HEADER = "page_header"
    SECTION_HEADER = "section_header"
    PAGE = "page"
    CELL = "cell"
    ROW = "row"
    COLUMN = "column"
    WORD = "word"
    LINE = "line"
    BACKGROUND = "background"
    PAGE_NUMBER = "page_number"
    KEY_VALUE_AREA = "key_value_area"
    LIST_ITEM = "list_item"
```

If there is a label missing I suggest to add a custom object type using this style:

@dd.object_types_registry.register("YOLOTYPE")
class YOLOTYPE(dd.ObjectTypes):
    """Additional YOLO labels not registered yet"""

    CUSTOM_OBJECT_TYPE ="custom_object_type",

This will avoid conflicts with very similar already registered enum members.

Let me know if this resolves you issue.

BTW: Would you be fine, if I can add your code to the docs on how to write a custom wrapper?

**Comment by adinath1233** [comment]
Hi, Thanks for your help, finally got it working.
Sure you can add this code, I have made some small changes in the wrapper class and it works.

Code: 

```
def _yolo_to_detectresult(results, categories) -> list[DetectionResult]:
    """
    Converts YOLO detection results into DetectionResult objects using inference speed as confidence.

    :param results: YOLO detection results
    :param categories: List of category names or LayoutType enums for YOLO classes.
    :return: A list of DetectionResult objects
    """

    all_results: list[DetectionResult] = []

    categories_name = categories.get_categories(as_dict=True)

            
    # Use inference speed as the confidence score (e.g., using 'inference' time as a proxy)
    confidence = results.speed.get('inference', 0) / 100  # Normalize by 100 if you want a scale between 0-1
    
    # Loop through each detected box
    for i, box in enumerate(results.boxes):
        # Extract and normalize bounding box coordinates
        x1, y1, x2, y2 = box.xyxy.tolist()[0]
        
        # Assign class_id based on detection order or results.boxes.cls if available
        class_id = int(box.cls)+1  # Get class ID based on available keys
        class_name = categories_name.get(class_id, "Unknown") # Directly retrieve the class name from categories
        
        # Create a DetectionResult object with inferred confidence
        detection = DetectionResult(
            box=[x1, y1, x2, y2],
            score=confidence,  # Set the normalized speed as confidence
            class_id=class_id,
            class_name=class_name
        )
        
        # Append the DetectionResult to the list
        all_results.append(detection)

    return all_results




def predict_yolo(np_img: PixelValues, model, conf_threshold: float = 0.2, iou_threshold: float = 0.8, categories:ModelCategories=None) -> list[DetectionResult]:
    """
    Run inference using the YOLO model.
    
    :param np_img: Input image as numpy array (BGR format)
    :param model: YOLO model instance
    :param conf_threshold: Confidence threshold for detections
    :param iou_threshold: Intersection-over-Union threshold for non-max suppression
    :param categories: List of category names or LayoutType enums for YOLO classes.
    :return: A list of detection results
    """
    # Run the model
    results = model(source=np_img, conf=conf_threshold, iou=iou_threshold)[0]
    
    # Convert results to DetectionResult format
    all_results = _yolo_to_detectresult(results, categories)
    
    return all_results


class YoloDetector(ObjectDetector):
    """
    Document detector using YOLO engine for layout analysis.
    
    Model weights must be placed at `.cache/deepdoctection/weights/yolo/`.
    
    The detector predicts different categories of document elements such as text, tables, figures, headers, etc.
    """
    def __init__(self, 
                 conf_threshold: float = 0.2, 
                 iou_threshold: float = 0.8, 
                 model_weights: PathLikeOrStr = None, 
                 categories: Mapping[int, TypeOrStr] = None) -> None:
        """
        :param conf_threshold: Confidence threshold for YOLO detections.
        :param iou_threshold: IoU threshold for YOLO detections.
        :param model_weights: Path to the YOLO model weights file.
        :param categories: List of category names or LayoutType enums for YOLO classes.
        """
        self.name = "yolo_detector"
        self.model_id = self.get_model_id()
        self.conf_threshold = conf_threshold
        self.iou_threshold = iou_threshold

        # Load YOLO model with specified weights
        self.model = YOLO(model_weights)

        if categories is None:
            raise ValueError("A dictionary of category mappings must be provided.")
        self.categories =ModelCategories(init_categories=categories)
    def predict(self, np_img: PixelValues) -> list[DetectionResult]:
        """
        Perform inference on a document image using YOLOv10 and return detection results.
        
        :param np_img: Input image as numpy array (BGR format)
        :return: A list of DetectionResult objects.
        """
        return predict_yolo(np_img, self.model, self.conf_threshold, self.iou_threshold, self.categories)

    @classmethod
    def get_requirements(cls) -> list[Requirement]:
        # No additional installation requirements as YOLO model is expected to be locally stored.
        return []

    def clone(self) -> YoloDetector:
        """
        Clone the current detector instance.
        """
        return self.__class__(conf_threshold=self.conf_threshold, 
                              iou_threshold=self.iou_threshold, 
                              model_weights=self.model.model_path)

    def get_category_names(self) -> tuple[ObjectTypes, ...]:
        """
        Get the category names used by YOLO for document detection.
        """
        return self.categories.get_categories(as_dict=False)

```

**Comment by JaMe76** [comment]
> Thank you for your kind words and for highlighting my contribution! I’m glad the YOLO integration and the extended example with Doclaynet are proving useful for the library and its community. It's exciting to see how it enhances the DeepDoctection Analyzer’s flexibility.
> 
> Regarding the Doclaynet with YOLO file, I noticed that my username is listed as "dinath1233" instead of "adinath1233." Could you please correct this?
> 
> Once again, thank you for your recognition and support—it’s been a pleasure contributing!

Thanks! Just updated your username.
